"""Stations curatées manuellement — sans pub, fiables."""

CURATED_STATIONS = [
    {
        "id": "chillhop",
        "name": "Chillhop Music",
        "stream_url": "https://streams.fluxfm.de/Chillhop/mp3-128/streams.fluxfm.de/",
        "homepage": "https://chillhop.com",
        "favicon": "https://chillhop.com/favicon.ico",
        "theme_ids": ["lofi", "focus"],
        "tags": ["lofi", "chillhop", "hip-hop"],
        "bitrate": 128,
        "codec": "mp3",
        "country": "Netherlands",
        "source": "curated",
    },
    {
        "id": "reyfm-lofi",
        "name": "REY FM Lofi",
        "stream_url": "https://listen.reyfm.de/lofi_320kbps.mp3",
        "homepage": "https://reyfm.de",
        "favicon": "",
        "theme_ids": ["lofi", "focus"],
        "tags": ["lofi", "chill"],
        "bitrate": 320,
        "codec": "mp3",
        "country": "Germany",
        "source": "curated",
    },
    {
        "id": "france-musique",
        "name": "France Musique",
        "stream_url": "https://icecast.radiofrance.fr/francemusique-hifi.aac",
        "homepage": "https://www.radiofrance.fr/francemusique",
        "favicon": "https://www.radiofrance.fr/favicon.ico",
        "theme_ids": ["classical"],
        "tags": ["classical", "opera", "contemporary"],
        "bitrate": 192,
        "codec": "aac",
        "country": "France",
        "source": "curated",
    },
    {
        "id": "jazz24",
        "name": "Jazz24",
        "stream_url": "https://live.wostreaming.net/manifest/ppm-jazz24aac256-ibc1.m3u8",
        "homepage": "https://www.jazz24.org",
        "favicon": "",
        "theme_ids": ["jazz"],
        "tags": ["jazz", "smooth jazz"],
        "bitrate": 256,
        "codec": "aac",
        "country": "United States",
        "source": "curated",
    },
    {
        "id": "wbgo",
        "name": "WBGO Jazz 88.3",
        "stream_url": "https://wbgo.streamguys1.com/wbgo128",
        "homepage": "https://www.wbgo.org",
        "favicon": "",
        "theme_ids": ["jazz"],
        "tags": ["jazz", "bebop", "blues"],
        "bitrate": 128,
        "codec": "mp3",
        "country": "United States",
        "source": "curated",
    },
    {
        "id": "nightwave-plaza",
        "name": "Nightwave Plaza",
        "stream_url": "http://radio.plaza.one/opus",
        "homepage": "https://plaza.one",
        "favicon": "https://plaza.one/favicon.ico",
        "theme_ids": ["lofi", "ambient", "electronic"],
        "tags": ["vaporwave", "lofi", "ambient"],
        "bitrate": 96,
        "codec": "opus",
        "country": "International",
        "source": "curated",
    },
    {
        "id": "cafe-del-mar",
        "name": "Café del Mar",
        "stream_url": "https://streams.radio.co/se1a320b47/listen",
        "homepage": "https://cafedelmarradio.com",
        "favicon": "",
        "theme_ids": ["ambient", "lofi", "focus"],
        "tags": ["chillout", "ambient", "balearic"],
        "bitrate": 128,
        "codec": "mp3",
        "country": "Spain",
        "source": "curated",
    },
    {
        "id": "radio-nova",
        "name": "Radio Nova",
        "stream_url": "http://novazz.ice.infomaniak.ch/novazz-128.mp3",
        "homepage": "https://www.nova.fr",
        "favicon": "https://www.nova.fr/favicon.ico",
        "theme_ids": ["world", "jazz", "electronic"],
        "tags": ["world", "soul", "funk", "jazz"],
        "bitrate": 128,
        "codec": "mp3",
        "country": "France",
        "source": "curated",
    },
]


def get_stations_for_themes(theme_ids: list[str]) -> list[dict]:
    if not theme_ids:
        return CURATED_STATIONS[:]
    return [
        s for s in CURATED_STATIONS
        if any(t in s["theme_ids"] for t in theme_ids)
    ]
